=== neoyogi/onepk/onepk_without_pyc/tutorials/applmgmt/cli_ext_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 3 sp1 (x64) (http://www.altova.com) by Lisa Huang (Cisco Systems, Inc.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cli_ext="http://www.cisco.com/onep/cli_ext:0.1" xmlns="http://www.cisco.com/onep/cli_ext:0.1" targetNamespace="http://www.cisco.com/onep/cli_ext:0.1" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="application">
        <xs:annotation>
            <xs:documentation>The application must have a name.  The name will be used as the top level CLI keyword.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:choice>
                    <xs:element name="config-cmds" type="config-cmds-type">
                        <xs:unique name="uniqueCommandName" id="uniqueCommandName">
                            <xs:annotation>
                                <xs:documentation>command name is unique.</xs:documentation>
                            </xs:annotation>
                            <xs:selector xpath="*"/>
                            <xs:field xpath="@name"/>
                        </xs:unique>
                    </xs:element>
                    <xs:element name="show-cmds" type="show-cmds-type"/>
                    <xs:element name="exec-cmds" type="exec-cmds-type"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="app-name" use="required">
                <xs:annotation>
                    <xs:documentation>This string is used as the entry level parser keyword.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="version" use="required">
                <xs:annotation>
                    <xs:documentation>This string is used as the version text in the parser.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="app-namespace" use="required">
                <xs:annotation>
                    <xs:documentation>Namespace used for the CLI app specific xsd.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:anyURI"/>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="app-namespace-prefix" use="required">
                <xs:annotation>
                    <xs:documentation>Namespace prefix used for the CLI app specific xsd.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="app-mode-prompt-prefix" use="required">
                <xs:annotation>
                    <xs:documentation>The prefix used for the CLI mode prompt.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="description" use="optional">
                <xs:annotation>
                    <xs:documentation>This string is used as the help text in the parser.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="255"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="show-cmds-type">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="exec-cmd" type="exec-cmd-type"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="exec-cmd-type">
        <xs:complexContent>
            <xs:extension base="cmd-type">
                <xs:sequence maxOccurs="unbounded">
                    <xs:choice minOccurs="1">
                        <xs:element name="keyword" type="optional-keyword-type" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element name="param" type="optional-param-type" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="config-cmds-type">
        <xs:sequence maxOccurs="unbounded">
            <xs:choice>
                <xs:element name="scalar-cmd" type="scalar-cmd-type" maxOccurs="unbounded"/>
                <xs:element name="list-cmd" type="list-cmd-type" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="exec-cmds-type">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="exec-cmd" type="exec-cmd-type" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="cmd-type">
        <xs:attribute name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="list-cmd-type">
        <xs:complexContent>
            <xs:extension base="cmd-type">
                <xs:sequence>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="keyword" type="keyword-type" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element name="param" type="cli_ext:key-param-type" maxOccurs="unbounded"/>
                    </xs:choice>
                    <xs:element name="mode" type="mode-type" minOccurs="0" maxOccurs="1">
                        <xs:unique name="uniquemodeCommandName">
                            <xs:annotation>
                                <xs:documentation>command name is unique.</xs:documentation>
                            </xs:annotation>
                            <xs:selector xpath="*"/>
                            <xs:field xpath="@name"/>
                        </xs:unique>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="keyword-type">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="help" type="helpType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="optional-keyword-type">
        <xs:complexContent>
            <xs:extension base="keyword-type">
                <xs:attribute name="is-optional" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="param-type">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="help" type="helpType"/>
            <xs:element name="type" type="onep-simple-type"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="key-param-type">
        <xs:complexContent>
            <xs:extension base="param-type">
                <xs:attribute name="is-key"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="optional-param-type">
        <xs:complexContent>
            <xs:extension base="param-type">
                <xs:attribute name="is-optional" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="scalar-cmd-type">
        <xs:complexContent>
            <xs:extension base="cmd-type">
                <xs:sequence>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="keyword" type="optional-keyword-type" maxOccurs="unbounded"/>
                        <xs:element name="param" type="optional-param-type" maxOccurs="unbounded"/>
                    </xs:choice>
                    <xs:element name="mode" type="mode-type" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="mode-type">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="scalar-cmd" type="scalar-cmd-type" maxOccurs="unbounded"/>
                <xs:element name="list-cmd" type="list-cmd-type" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="mode-prompt" use="required">
            <xs:annotation>
                <xs:documentation>This string is used as mode prompt.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                    <xs:maxLength value="100"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="onep-simple-type">
        <xs:choice>
            <xs:element name="string">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="pattern" type="xs:string" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>The value (xs:pattern value) must be a ·regular expression· as defined in W3C XML Schema Definition Language (XSD) 1.1. http://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#regexs</xs:documentation>
                            </xs:annotation>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <!--<xs:element name="enumeration">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="value" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>-->
            <xs:element name="integer">
                <xs:complexType>
                    <xs:sequence minOccurs="0">
                        <xs:element name="min" type="xs:integer" minOccurs="1">
                            <xs:annotation>
                                <xs:documentation>minInclusive</xs:documentation>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="max" type="xs:integer" minOccurs="1">
                            <xs:annotation>
                                <xs:documentation>maxInclusive</xs:documentation>
                            </xs:annotation>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="ipv4-address"/>
            <xs:element name="ipv6-address"/>
            <xs:element name="ipv4-mask"/>
            <xs:element name="ipv6-mask"/>
        </xs:choice>
    </xs:complexType>
    <xs:simpleType name="helpType">
        <xs:annotation>
            <xs:documentation>Description string</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <!--<xs:pattern value="[&#x20;-&#x21;&#x23;-&#x26;&#x28;-&#x7E;]*"/>-->
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ipv4-address">
        <xs:annotation>
            <xs:documentation>The ipv4-address type represents an IPv4 address in
        dotted-quad notation.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="ipv6-address">
        <xs:annotation>
            <xs:documentation>The ipv6-address type represents an IPv6 address in full,
      and shortened notation. </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="ipv4-mask">
        <xs:annotation>
            <xs:documentation>The ipv4-mask type represents an IPv4 address mask in
        dotted-quad notation.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="ipv6-mask">
        <xs:annotation>
            <xs:documentation>The ipv6-mask type represents an IPv6 address mask in full,
      and shortened notation. </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:complexType name="string_key_attr_abstract">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="key"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="integer_key_attr_abstract">
        <xs:simpleContent>
            <xs:extension base="xs:integer">
                <xs:attribute name="key"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== neoyogi/onepk/onepk_without_pyc/tutorials/applmgmt/cli_ext_tutorial_app.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
config
    app-category name <name>
 
    app-stats <stat>
          user user-count <count> 
          price amount <amount>
          

show 
          sh onep application cli_tutorial_app v0.2 <config-domain> [<instance-name>] app-category
          sh onep application cli_tutorial_app v0.2 <config-domain> [<instance-name>] statistics
          
-->
<?xml-stylesheet type="text/xsl" href="xml2xsd-convertor.xslt"?>
<cli_ext:application app-name="cli_tutorial_app" version="0.2" description="Cli Extension Tutorial Application" app-namespace-prefix="demo" app-mode-prompt-prefix="demo" app-namespace="http://www.cisco.com/demo_app" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cli_ext="http://www.cisco.com/onep/cli_ext:0.1" xsi:schemaLocation="http://www.cisco.com/onep/cli_ext:0.1 cli_ext_schema.xsd">
  <cli_ext:config-cmds>
    <cli_ext:scalar-cmd name="app_category_cmd">
      <cli_ext:keyword>
        <cli_ext:name>app-category</cli_ext:name>
        <cli_ext:help>config onep app category name</cli_ext:help>
      </cli_ext:keyword>
      <cli_ext:param>
		<cli_ext:name>name</cli_ext:name>
		<cli_ext:help>string</cli_ext:help>
		<cli_ext:type>
				<cli_ext:string/>
		</cli_ext:type>
	  </cli_ext:param>
    </cli_ext:scalar-cmd>
     <cli_ext:list-cmd name="app_stat_cmd">
     		<cli_ext:param>
			 <cli_ext:name>app-stats</cli_ext:name>
				<cli_ext:help>add app statistics</cli_ext:help>
				<cli_ext:type>
					<cli_ext:string/>
				</cli_ext:type>
				</cli_ext:param>
        <cli_ext:mode mode-prompt="stat">
        <cli_ext:scalar-cmd name="users_cmd">
		<cli_ext:keyword>
			<cli_ext:name>users</cli_ext:name>
			<cli_ext:help>Number of users</cli_ext:help>
		</cli_ext:keyword>
		<cli_ext:param>
			<cli_ext:name>count</cli_ext:name>
			<cli_ext:help>count</cli_ext:help>
			<cli_ext:type>
				<cli_ext:integer/>
			</cli_ext:type>
		</cli_ext:param>
		</cli_ext:scalar-cmd>
		<cli_ext:scalar-cmd name="price_cmd">
		<cli_ext:keyword>
			<cli_ext:name>price</cli_ext:name>
			<cli_ext:help>purchase price</cli_ext:help>
		</cli_ext:keyword>
		<cli_ext:param>
			<cli_ext:name>amount</cli_ext:name>
			<cli_ext:help>number</cli_ext:help>
			<cli_ext:type>
				<cli_ext:integer/>
			</cli_ext:type>
		</cli_ext:param>
		</cli_ext:scalar-cmd>
		</cli_ext:mode>
		</cli_ext:list-cmd>
  </cli_ext:config-cmds>
  <cli_ext:show-cmds>
	<cli_ext:exec-cmd name="show_category_cmd">
			<cli_ext:keyword>
				<cli_ext:name>app-category</cli_ext:name>
				<cli_ext:help>show onep app's category name</cli_ext:help>
			</cli_ext:keyword>
	</cli_ext:exec-cmd>
	<cli_ext:exec-cmd name="show_stat_cmd">
			<cli_ext:keyword>
				<cli_ext:name>statistics</cli_ext:name>
				<cli_ext:help>onep app statistics</cli_ext:help>
			</cli_ext:keyword>
	</cli_ext:exec-cmd>
  </cli_ext:show-cmds>
  
  <cli_ext:exec-cmds>
		<cli_ext:exec-cmd name="clear_stat_cmd">
			<cli_ext:keyword>
				<cli_ext:name>clear</cli_ext:name>
				<cli_ext:help>clear</cli_ext:help>
			</cli_ext:keyword>
			<cli_ext:keyword>
				<cli_ext:name>statistics</cli_ext:name>
				<cli_ext:help>statistics</cli_ext:help>
			</cli_ext:keyword>
		
		</cli_ext:exec-cmd>
	</cli_ext:exec-cmds>
</cli_ext:application>
